import { ChampionAttributes } from './types'

export const CHAMPIONS_DATABASE: ChampionAttributes[] = [
  {
    id: 'garen',
    name: 'Garen',
    title: 'Might of Demacia',
    roles: ['top'],
    primaryDamage: 'AD',
    styles: ['engage', 'tank', 'dps'],
    difficulty: 1,
    strength: 7,
    popularity: 8,
    strongAgainst: ['darius', 'mordekaiser', 'teemo'],
    weakAgainst: ['kled', 'quinn', 'kayle'],
    synergizesWith: ['amumu', 'galio', 'malphite'],
    clashesWith: ['vayne', 'fiora'],
    engageTools: true,
    peelingTools: false,
    scalingPotential: true,
    earlyGamePower: true,
    teamFightPresence: true,
  },
  {
    id: 'gnar',
    name: 'Gnar',
    title: 'The Missing Link',
    roles: ['top'],
    primaryDamage: 'AD',
    styles: ['engage', 'poke', 'tank'],
    difficulty: 4,
    strength: 8,
    popularity: 6,
    strongAgainst: ['riven', 'jax', 'fiora'],
    weakAgainst: ['vladimir', 'maokai', 'lissandra'],
    synergizesWith: ['amumu', 'kennen', 'yasuo'],
    clashesWith: ['gragas'],
    engageTools: true,
    peelingTools: false,
    scalingPotential: true,
    earlyGamePower: true,
    teamFightPresence: true,
  },
  {
    id: 'twisted-fate',
    name: 'Twisted Fate',
    title: 'The Card Master',
    roles: ['mid'],
    primaryDamage: 'Mixed',
    styles: ['poke', 'burst', 'scaling', 'utility'],
    difficulty: 4,
    strength: 7,
    popularity: 5,
    strongAgainst: ['syndra', 'ahri', 'zed'],
    weakAgainst: ['orianna', 'leblanc', 'fizz'],
    synergizesWith: ['ashe', 'caitlyn', 'leona'],
    clashesWith: ['katarina', 'ryze'],
    engageTools: true,
    peelingTools: false,
    scalingPotential: true,
    earlyGamePower: false,
    teamFightPresence: true,
  },
  {
    id: 'katarina',
    name: 'Katarina',
    title: 'The Sinister Blade',
    roles: ['mid'],
    primaryDamage: 'AP',
    styles: ['burst', 'engage', 'dps'],
    difficulty: 3,
    strength: 8,
    popularity: 9,
    strongAgainst: ['yasuo', 'irelia', 'zed'],
    weakAgainst: ['galio', 'kassadin', 'ahri'],
    synergizesWith: ['amumu', 'malphite', 'jarvan'],
    clashesWith: ['twisted-fate'],
    engageTools: true,
    peelingTools: false,
    scalingPotential: true,
    earlyGamePower: false,
    teamFightPresence: true,
  },
  {
    id: 'ahri',
    name: 'Ahri',
    title: 'The Nine-Tailed Fox',
    roles: ['mid'],
    primaryDamage: 'AP',
    styles: ['burst', 'poke', 'scaling'],
    difficulty: 2,
    strength: 8,
    popularity: 9,
    strongAgainst: ['annie', 'ryze', 'talon'],
    weakAgainst: ['katarina', 'fizz', 'yasuo'],
    synergizesWith: ['leona', 'nautilus', 'alistar'],
    clashesWith: ['katarina', 'yasuo'],
    engageTools: true,
    peelingTools: true,
    scalingPotential: true,
    earlyGamePower: false,
    teamFightPresence: true,
  },
  {
    id: 'lee-sin',
    name: 'Lee Sin',
    title: 'The Blind Monk',
    roles: ['jungle'],
    primaryDamage: 'AD',
    styles: ['engage', 'burst', 'dps'],
    difficulty: 5,
    strength: 8,
    popularity: 8,
    strongAgainst: ['graves', 'karthus', 'kindred'],
    weakAgainst: ['elise', 'nidalee', 'taliyah'],
    synergizesWith: ['garen', 'darius', 'pantheon'],
    clashesWith: ['fiddlesticks'],
    engageTools: true,
    peelingTools: false,
    scalingPotential: false,
    earlyGamePower: true,
    teamFightPresence: true,
  },
  {
    id: 'amumu',
    name: 'Amumu',
    title: 'The Sad Mummy',
    roles: ['jungle', 'mid'],
    primaryDamage: 'AP',
    styles: ['engage', 'tank', 'dps'],
    difficulty: 2,
    strength: 7,
    popularity: 7,
    strongAgainst: ['lee-sin', 'graves', 'shaco'],
    weakAgainst: ['elise', 'nidalee', 'leblanc'],
    synergizesWith: ['katarina', 'ahri', 'darius'],
    clashesWith: ['warwick'],
    engageTools: true,
    peelingTools: false,
    scalingPotential: true,
    earlyGamePower: false,
    teamFightPresence: true,
  },
  {
    id: 'vayne',
    name: 'Vayne',
    title: 'The Night Hunter',
    roles: ['adc'],
    primaryDamage: 'AD',
    styles: ['burst', 'dps', 'scaling'],
    difficulty: 4,
    strength: 8,
    popularity: 7,
    strongAgainst: ['garen', 'maokai', 'darius'],
    weakAgainst: ['blitzcrank', 'thresh', 'leona'],
    synergizesWith: ['braum', 'karma', 'lulu'],
    clashesWith: ['leona', 'blitzcrank'],
    engageTools: false,
    peelingTools: false,
    scalingPotential: true,
    earlyGamePower: false,
    teamFightPresence: true,
  },
  {
    id: 'caitlyn',
    name: 'Caitlyn',
    title: 'Sheriff of Piltover',
    roles: ['adc'],
    primaryDamage: 'AD',
    styles: ['poke', 'dps', 'scaling'],
    difficulty: 2,
    strength: 8,
    popularity: 8,
    strongAgainst: ['ashe', 'mf', 'varus'],
    weakAgainst: ['akali', 'zyra', 'karma'],
    synergizesWith: ['leona', 'nautilus', 'braum'],
    clashesWith: ['zyra'],
    engageTools: false,
    peelingTools: false,
    scalingPotential: true,
    earlyGamePower: true,
    teamFightPresence: true,
  },
  {
    id: 'ashe',
    name: 'Ashe',
    title: 'The Frost Archer',
    roles: ['adc'],
    primaryDamage: 'AD',
    styles: ['poke', 'dps', 'utility'],
    difficulty: 1,
    strength: 7,
    popularity: 6,
    strongAgainst: ['kalista', 'draven', 'samira'],
    weakAgainst: ['zeri', 'kaisa', 'jhin'],
    synergizesWith: ['leona', 'braum', 'thresh'],
    clashesWith: ['zeri'],
    engageTools: false,
    peelingTools: false,
    scalingPotential: true,
    earlyGamePower: true,
    teamFightPresence: true,
  },
  {
    id: 'leona',
    name: 'Leona',
    title: 'The Radiant Dawn',
    roles: ['support'],
    primaryDamage: 'AD',
    styles: ['engage', 'tank', 'peel'],
    difficulty: 2,
    strength: 8,
    popularity: 8,
    strongAgainst: ['blitzcrank', 'pyke', 'thresh'],
    weakAgainst: ['bard', 'karma', 'vel-koz'],
    synergizesWith: ['vayne', 'caitlyn', 'ashe'],
    clashesWith: ['bard'],
    engageTools: true,
    peelingTools: true,
    scalingPotential: false,
    earlyGamePower: true,
    teamFightPresence: true,
  },
  {
    id: 'thresh',
    name: 'Thresh',
    title: 'The Chain Warden',
    roles: ['support'],
    primaryDamage: 'AD',
    styles: ['engage', 'peel', 'utility'],
    difficulty: 5,
    strength: 8,
    popularity: 8,
    strongAgainst: ['leona', 'blitzcrank', 'senna'],
    weakAgainst: ['pyke', 'bard', 'karma'],
    synergizesWith: ['draven', 'samira', 'kalista'],
    clashesWith: ['leona'],
    engageTools: true,
    peelingTools: true,
    scalingPotential: true,
    earlyGamePower: true,
    teamFightPresence: true,
  },
  {
    id: 'braum',
    name: 'Braum',
    title: 'The Heart of the Freljord',
    roles: ['support'],
    primaryDamage: 'AD',
    styles: ['tank', 'peel', 'engage'],
    difficulty: 2,
    strength: 7,
    popularity: 6,
    strongAgainst: ['pyke', 'lux', 'brand'],
    weakAgainst: ['alistar', 'nautilus', 'zyra'],
    synergizesWith: ['vayne', 'ashe', 'caitlyn'],
    clashesWith: ['alistar'],
    engageTools: true,
    peelingTools: true,
    scalingPotential: false,
    earlyGamePower: false,
    teamFightPresence: true,
  },
  {
    id: 'blitzcrank',
    name: 'Blitzcrank',
    title: 'The Great Steam Golem',
    roles: ['support'],
    primaryDamage: 'AD',
    styles: ['engage', 'tank', 'peel'],
    difficulty: 2,
    strength: 7,
    popularity: 7,
    strongAgainst: ['senna', 'lulu', 'janna'],
    weakAgainst: ['karma', 'leona', 'thresh'],
    synergizesWith: ['mf', 'jhin', 'draven'],
    clashesWith: ['leona'],
    engageTools: true,
    peelingTools: false,
    scalingPotential: false,
    earlyGamePower: true,
    teamFightPresence: true,
  },
  {
    id: 'darius',
    name: 'Darius',
    title: 'The Hand of Noxus',
    roles: ['top'],
    primaryDamage: 'AD',
    styles: ['engage', 'dps', 'burst'],
    difficulty: 2,
    strength: 8,
    popularity: 8,
    strongAgainst: ['garen', 'malphite', 'maokai'],
    weakAgainst: ['teemo', 'kled', 'quinn'],
    synergizesWith: ['amumu', 'jarvan', 'malphite'],
    clashesWith: ['vayne'],
    engageTools: true,
    peelingTools: false,
    scalingPotential: true,
    earlyGamePower: true,
    teamFightPresence: true,
  },
  {
    id: 'maokai',
    name: 'Maokai',
    title: 'The Twisted Treant',
    roles: ['top', 'support'],
    primaryDamage: 'AP',
    styles: ['engage', 'tank', 'peel'],
    difficulty: 2,
    strength: 7,
    popularity: 5,
    strongAgainst: ['darius', 'garen', 'fiora'],
    weakAgainst: ['ryze', 'vladimir', 'teemo'],
    synergizesWith: ['katarina', 'ahri', 'amumu'],
    clashesWith: ['vladimir'],
    engageTools: true,
    peelingTools: true,
    scalingPotential: true,
    earlyGamePower: false,
    teamFightPresence: true,
  },
  {
    id: 'yasuo',
    name: 'Yasuo',
    title: 'The Unforgiven',
    roles: ['mid', 'adc'],
    primaryDamage: 'AD',
    styles: ['burst', 'dps', 'engage'],
    difficulty: 5,
    strength: 8,
    popularity: 8,
    strongAgainst: ['galio', 'zed', 'talon'],
    weakAgainst: ['ahri', 'katarina', 'orianna'],
    synergizesWith: ['gnar', 'kennen', 'amumu'],
    clashesWith: ['galio'],
    engageTools: true,
    peelingTools: false,
    scalingPotential: true,
    earlyGamePower: false,
    teamFightPresence: true,
  },
  {
    id: 'lux',
    name: 'Lux',
    title: 'The Lady of Luminosity',
    roles: ['mid', 'support'],
    primaryDamage: 'AP',
    styles: ['burst', 'poke', 'utility'],
    difficulty: 2,
    strength: 7,
    popularity: 7,
    strongAgainst: ['talon', 'zed', 'yasuo'],
    weakAgainst: ['leblanc', 'kassadin', 'fizz'],
    synergizesWith: ['blitzcrank', 'ashe', 'caitlyn'],
    clashesWith: ['leblanc'],
    engageTools: false,
    peelingTools: true,
    scalingPotential: true,
    earlyGamePower: false,
    teamFightPresence: true,
  },
  {
    id: 'ryze',
    name: 'Ryze',
    title: 'The Rogue Mage',
    roles: ['mid'],
    primaryDamage: 'AP',
    styles: ['burst', 'dps', 'scaling', 'utility'],
    difficulty: 4,
    strength: 7,
    popularity: 4,
    strongAgainst: ['zed', 'talon', 'yasuo'],
    weakAgainst: ['ahri', 'leblanc', 'syndra'],
    synergizesWith: ['amumu', 'malphite', 'jarvan'],
    clashesWith: ['ahri'],
    engageTools: false,
    peelingTools: false,
    scalingPotential: true,
    earlyGamePower: false,
    teamFightPresence: true,
  },
]

export function getChampionById(id: string): ChampionAttributes | undefined {
  return CHAMPIONS_DATABASE.find((c) => c.id === id)
}

export function getChampionsByRole(role: string): ChampionAttributes[] {
  return CHAMPIONS_DATABASE.filter((c) => c.roles.includes(role as any))
}

export function searchChampions(query: string): ChampionAttributes[] {
  const lower = query.toLowerCase()
  return CHAMPIONS_DATABASE.filter(
    (c) => c.name.toLowerCase().includes(lower) || c.id.includes(lower)
  )
}
